language: node_js
node_js:
  - 12

services:
  - docker

script:
  - docker --version # print the version for logging
#  - docker build -t udagram-api-feed ./udagram-api-feed
#  - docker build -t udagram-api-user ./udagram-api-user
#  - docker build -t udagram-frontend ./udagram-frontend
#  - docker build -t udagram-reverseproxy ./udagram-reverseproxy


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#  - docker push massony875/udagram-api-feed:v1.1
#  - docker push massony875/udagram-api-user:v1.1
#  - docker push massony875/udagram-frontend:v1.1
#  - docker push massony875/reverseproxy:v1.1

