language: node_js
node_js:
  - 12

services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.27.4

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin


script:
  - docker --version # print the version for logging
  - docler-compose --version
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag reverseproxy  massony875/reverseproxy:v1.1
  - docker tag udagram-frontend:local massony875/udagram-frontend:v1.1
  - docker tag udagram-api-feed massony875/udagram-api-feed:v1.1
  - docker tag udagram-api-user massony875/udagram-api-user:v1.1


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push massony875/udagram-api-feed:v1.1
  - docker push massony875/udagram-api-user:v1.1
  - docker push massony875/udagram-frontend:v1.1
  - docker push massony875/reverseproxy:v1.1

