apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: udagram3
  region: us-east-1

nodeGroups:
  - name: udagram3-ng
    instanceType: m5.large
    desiredCapacity: 3
    ssh:
      publicKeyName: us-east-1-key-pair
