apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: udagram
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: udagram
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: massony875/udagram-frontend:v1.1.1
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8100

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: udagram
    tier: frontend
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  ports:
    - port: 8100
  selector:
    app: udagram
    tier: frontend
